version: "1"

# varaha-cache CI/CD pipeline

metadata:
  template: false

secrets:
  - name: kaniko_username
    key: prioarc-apps/varaha-cache/harbor_username
    engine: native
    type: repo

  - name: kaniko_password
    key: prioarc-apps/varaha-cache/harbor_password
    engine: native
    type: repo

steps:
  - name: fmt
    image: rust:1.87-slim
    pull: always
    commands:
      - rustup component add rustfmt
      - cargo fmt --all -- --check

  - name: clippy
    image: rust:1.87-slim
    pull: always
    commands:
      - rustup component add clippy
      - cargo clippy --workspace --all-targets -- -D warnings

  - name: test
    image: rust:1.87-slim
    pull: always
    commands:
      - cargo test --workspace

  - name: build
    image: rust:1.87-slim
    pull: always
    commands:
      - cargo build --workspace --release

  - name: docker-build-push
    image: target/vela-kaniko:latest
    pull: always
    secrets: [kaniko_username, kaniko_password]
    ruleset:
      branch: [main]
      event: [push]
    parameters:
      registry: registry.intra.varaha.io
      repo: registry.intra.varaha.io/varaha/varaha-cache
      tags:
        - latest
        - "build-${VELA_BUILD_NUMBER}"
      build_args:
        - "RUST_VERSION=1.87"
