[package]
name = "rv-transport"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "HTTP/1.1, HTTP/2, and PROXY protocol transport"

[dependencies]
rv-types = { workspace = true }
rv-http = { workspace = true }
rv-cache = { workspace = true }
rv-backend = { workspace = true }
tokio = { workspace = true }
hyper = { workspace = true }
http = { workspace = true }
h2 = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
rustls = { workspace = true }
tokio-rustls = { workspace = true }
rustls-pemfile = { workspace = true }
tokio-util = { workspace = true }

[dev-dependencies]
ring = { workspace = true }
base64 = { workspace = true }
